services:
  drivers-service:
    build: ../microservices/drivers-service
    ports:
      - "${DRV_PORT}:${DRV_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DRV_POSTGRES_DB}
      DRV_PORT: ${DRV_PORT}
    depends_on:
      - postgres-db

  passengers-service:
    build: ../microservices/passengers-service
    ports:
      - "${PSG_PORT}:${PSG_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${PSG_POSTGRES_DB}
      PSG_PORT: ${PSG_PORT}
    depends_on:
      - postgres-db

  trips-service:
    build: ../microservices/trips-service
    ports:
      - "${TRP_PORT}:${TRP_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TRP_POSTGRES_DB}
      TRP_PORT: ${TRP_PORT}
    depends_on:
      - postgres-db
      - passengers-service
      - drivers-service
      - location-service

  location-service:
    build: ../microservices/location-service
    ports:
      - "${LOC_PORT}:${LOC_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOC_POSTGRES_DB}
      LOC_PORT: ${LOC_PORT}
    depends_on:
      - postgres-db
      - drivers-service

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d

volumes:
  pg-data: